name: Selenium tests
# This will run all the tests in backend/src/test/java/com/example/backend/rest using JDK 18
on:
  push:
    branches:
      - main
      - ci-cd
  pull_request:
    branches:
      - main
      - ci-cd

jobs:
  selenium-tests:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "18"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: "131"
          install-dependencies: true
          install-chromedriver: true

      - name: Set up Docker (database container setup)
        run: sudo docker run -d --name bookmarks-forums-DB-GitHub-actions-selenium -p 3306:3306 -e MYSQL_DATABASE=BFDB -e MYSQL_ROOT_PASSWORD=password mysql:8.3.0

      - name: Install Dockerize
        run: curl -sSL https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz | sudo tar -C /usr/local/bin -xzv

      - name: Wait for MySQL to start
        run: dockerize -wait tcp://localhost:3306 -timeout 1m

      - name: Set environment variables
        run: |
          echo "GMAIL_USERNAME=${{ secrets.GMAIL_USERNAME }}" >> $GITHUB_ENV
          echo "GMAIL_PASSWORD=${{ secrets.GMAIL_PASSWORD }}" >> $GITHUB_ENV

      - name: Create env.properties file
        run: |
          echo "GMAIL_USERNAME=${{ secrets.GMAIL_USERNAME }}" > backend/src/main/resources/env.properties
          echo "GMAIL_PASSWORD=${{ secrets.GMAIL_PASSWORD }}" >> backend/src/main/resources/env.properties

      - name: Convert line endings to Unix format
        run: sed -i 's/\r$//' backend/mvnw

      - name: Make mvnw executable
        run: chmod +x backend/mvnw
    
      - name: Build with Maven
        run: backend/mvnw -B package --file backend/pom.xml -DskipTests

      - name: Run application
        run: |
          nohup backend/mvnw spring-boot:run --file backend/pom.xml &
          sleep 10

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Angular CLI
        run: npm install -g @angular/cli
        working-directory: frontend

      - name: Do not share the Angular CLI telemetry data
        run: ng analytics off
        working-directory: frontend

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Run Angular application
        run: |
          nohup ng serve &
          sleep 30
        working-directory: frontend

      - name: Run Selenium tests
        run: backend/mvnw test -P selenium-tests --file backend/pom.xml
